MODULE modmain
use m_lattice
use m_atoms
use m_atomic_species
use m_muffin_tins
use m_spin
use m_electric_vector_pot
use m_symmetry
use m_gvectors
use m_kpoints
use m_gkvectors
use m_qpoints
use m_sht
use m_density_pot_xc
use m_mixing
use m_charge_moment_current
use m_apwlo
use m_hamiltonian
use m_states
use m_core_states
use m_energy
use m_force_stress
use m_convergence
use m_dos_optics_response
use m_plotting
use m_oep_hf
!use m_respfunc_perturb
use m_bse
use m_timing
use m_constants
use m_misc
END MODULE 